// Generated by scripts/generate-tsrx-types.mjs.
import type { EdgeBase, NodeBase, SmartEdgeProps } from './types.js';
export declare function SmartEdge<
	EdgeType extends EdgeBase = EdgeBase,
	NodeType extends NodeBase = NodeBase,
>(
	props: Readonly<SmartEdgeProps<EdgeType, NodeType>>,
): import('octane/jsx-runtime').Octane.JSX.Element;
