// Generated by scripts/generate-tsrx-types.mjs.
import type { DocumentContextType, OutlineContextType, PageContextType } from './types';
export declare const DocumentContext: import('octane').Context<DocumentContextType>;
export declare const PageContext: import('octane').Context<PageContextType>;
export declare const OutlineContext: import('octane').Context<OutlineContextType>;
export declare function useDocumentContext(): DocumentContextType;
export declare function usePageContext(): PageContextType;
export declare function useOutlineContext(): OutlineContextType;
