// Generated by scripts/generate-tsrx-types.mjs.
import type { PDFDocumentProxy } from 'pdfjs-dist';
import type {
	ClassName,
	DocumentHandle,
	DocumentRenderProps,
	ExternalLinkRel,
	ExternalLinkTarget,
	File,
	HostProps,
	ImageResourcesPath,
	NodeOrRenderer,
	OnItemClickArgs,
	OnLoadProgressArgs,
	OnPasswordCallback,
	Options,
	PasswordResponse,
	Ref,
	RenderMode,
} from './types';
export type DocumentProps = {
	children?:
		import('octane').OctaneNode | ((props: DocumentRenderProps) => import('octane').OctaneNode);
	className?: ClassName;
	error?: NodeOrRenderer;
	externalLinkRel?: ExternalLinkRel;
	externalLinkTarget?: ExternalLinkTarget;
	file?: File;
	imageResourcesPath?: ImageResourcesPath;
	inputRef?: Ref<HTMLDivElement>;
	loading?: NodeOrRenderer;
	noData?: NodeOrRenderer;
	onItemClick?: (args: OnItemClickArgs) => void;
	onLoadError?: (error: Error) => void;
	onLoadProgress?: (args: OnLoadProgressArgs) => void;
	onLoadSuccess?: (document: PDFDocumentProxy) => void;
	onPassword?: (callback: OnPasswordCallback, reason: PasswordResponse) => void;
	onSourceError?: (error: Error) => void;
	onSourceSuccess?: () => void;
	options?: Options;
	ref?: Ref<DocumentHandle>;
	renderMode?: RenderMode;
	rotate?: number | null;
	scale?: number;
} & HostProps<HTMLDivElement>;
export default function Document({
	children,
	className,
	error,
	externalLinkRel,
	externalLinkTarget,
	file,
	imageResourcesPath,
	inputRef,
	loading,
	noData,
	onItemClick,
	onLoadError,
	onLoadProgress,
	onLoadSuccess,
	onPassword,
	onSourceError,
	onSourceSuccess,
	options,
	ref,
	renderMode,
	rotate,
	scale,
	...hostProps
}: DocumentProps): import('octane/jsx-runtime').Octane.JSX.Element;
