// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
export type MessageProps = {
	children?: OctaneNode;
	type: 'error' | 'loading' | 'no-data';
};
export default function Message({
	children,
	type,
}: MessageProps): import('octane/jsx-runtime').Octane.JSX.Element;
