// Generated by scripts/generate-tsrx-types.mjs.
import type { PDFDocumentProxy } from 'pdfjs-dist';
import type { ClassName, HostProps, OnItemClickArgs, Ref } from './types';
type PDFOutline = NonNullable<Awaited<ReturnType<PDFDocumentProxy['getOutline']>>>;
export type OutlineProps = {
	className?: ClassName;
	inputRef?: Ref<HTMLDivElement>;
	onItemClick?: (props: OnItemClickArgs) => void;
	onLoadError?: (error: Error) => void;
	onLoadSuccess?: (outline: PDFOutline | null) => void;
	pdf?: PDFDocumentProxy | false;
} & HostProps<HTMLDivElement>;
export default function Outline(props: OutlineProps): any;
export {};
