// Generated by scripts/generate-tsrx-types.mjs.
import type { PDFDocumentProxy } from 'pdfjs-dist';
import type LinkService from './LinkService';
type PDFOutline = NonNullable<Awaited<ReturnType<PDFDocumentProxy['getOutline']>>>;
type PDFOutlineItem = PDFOutline[number];
export type OutlineItemProps = {
	item: PDFOutlineItem;
	linkService?: LinkService;
	pdf: PDFDocumentProxy;
};
export default function OutlineItem({ item, linkService, pdf }: OutlineItemProps): any;
export {};
