// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
import type { PDFDocumentProxy } from 'pdfjs-dist';
import type { StructTreeNode, TextContent } from 'pdfjs-dist/types/src/display/api.js';
import type {
	Annotations,
	ClassName,
	CustomRenderer,
	CustomTextRenderer,
	FilterAnnotations,
	HostProps,
	NodeOrRenderer,
	PageCallback,
	PageColors,
	PageRenderProps,
	Ref,
	RenderMode,
} from './types';
export type PageProps = {
	_className?: string;
	_enableRegisterUnregisterPage?: boolean;
	canvasBackground?: string;
	canvasRef?: Ref<HTMLCanvasElement>;
	children?: OctaneNode | ((props: PageRenderProps) => OctaneNode);
	className?: ClassName;
	customRenderer?: CustomRenderer;
	customTextRenderer?: CustomTextRenderer;
	devicePixelRatio?: number;
	error?: NodeOrRenderer;
	filterAnnotations?: FilterAnnotations;
	height?: number;
	imageResourcesPath?: string;
	inputRef?: Ref<HTMLDivElement>;
	loading?: NodeOrRenderer;
	noData?: NodeOrRenderer;
	onGetAnnotationsError?: (error: Error) => void;
	onGetAnnotationsSuccess?: (annotations: Annotations) => void;
	onGetStructTreeError?: (error: Error) => void;
	onGetStructTreeSuccess?: (tree: StructTreeNode) => void;
	onGetTextError?: (error: Error) => void;
	onGetTextSuccess?: (text: TextContent) => void;
	onLoadError?: (error: Error) => void;
	onLoadSuccess?: (page: PageCallback) => void;
	onRenderAnnotationLayerError?: (error: unknown) => void;
	onRenderAnnotationLayerSuccess?: () => void;
	onRenderError?: (error: Error) => void;
	onRenderSuccess?: (page: PageCallback) => void;
	onRenderTextLayerError?: (error: Error) => void;
	onRenderTextLayerSuccess?: () => void;
	pageColors?: PageColors;
	pageIndex?: number;
	pageNumber?: number;
	pdf?: PDFDocumentProxy | false;
	renderAnnotationLayer?: boolean;
	renderForms?: boolean;
	renderMode?: RenderMode;
	renderTextLayer?: boolean;
	rotate?: number | null;
	scale?: number;
	width?: number;
} & Omit<HostProps<HTMLDivElement>, 'style'>;
export default function Page(props: PageProps): import('octane/jsx-runtime').Octane.JSX.Element;
