// Generated by scripts/generate-tsrx-types.mjs.
import type { StructTreeContent } from 'pdfjs-dist/types/src/display/api.js';
import type { StructTreeNodeWithExtraAttributes } from './structTreeUtils';
export type StructTreeItemProps = {
	className?: string;
	node: StructTreeNodeWithExtraAttributes | StructTreeContent;
};
export default function StructTreeItem({ className, node }: StructTreeItemProps): any;
