// Generated by scripts/generate-tsrx-types.mjs.
import type { PageProps } from './Page.tsrx';
import type { ClassName, OnItemClickArgs } from './types';
export type ThumbnailProps = Omit<
	PageProps,
	| 'className'
	| 'customTextRenderer'
	| 'onGetAnnotationsError'
	| 'onGetAnnotationsSuccess'
	| 'onGetTextError'
	| 'onGetTextSuccess'
	| 'onRenderAnnotationLayerError'
	| 'onRenderAnnotationLayerSuccess'
	| 'onRenderTextLayerError'
	| 'onRenderTextLayerSuccess'
	| 'renderAnnotationLayer'
	| 'renderForms'
	| 'renderTextLayer'
> & {
	className?: ClassName;
	onItemClick?: (args: OnItemClickArgs) => void;
};
export default function Thumbnail(
	props: ThumbnailProps,
): import('octane/jsx-runtime').Octane.JSX.Element;
