// Generated by scripts/generate-tsrx-types.mjs.
import type { Ref } from '../types';
export type CanvasProps = {
	canvasRef?: Ref<HTMLCanvasElement>;
};
export default function Canvas({
	canvasRef,
}: CanvasProps): import('octane/jsx-runtime').Octane.JSX.Element;
